### PR TITLE
Changed react/socket to 0.8

### PR DESCRIPTION
**Pull request by skaffille**
Updated dependencies to other libraries to allow usage of react/socket 0.8.11
Changed streams and usage of timer.
Adapted unit tests.

### CODE REVIEW

**Comment by skaffille** [comment]
I will fix the PHP 5.6 issues as soon as possible.
Regarding the activemq issues ... there are some installation problems during the build for all PHP versions 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tree
cp: cannot create regular file ‘/etc/activemq/instances-available/main/’: No such file or directory
ln: failed to create symbolic link ‘/etc/activemq/instances-enabled/main’: No such file or directory
activemq: unrecognized service
```

**Comment by skaffille** [comment]
Build works for php5.6 now, as well.
activemq still failing...

**Comment by brettmc** [comment]
@skaffille I came across those failures with https://github.com/friends-of-reactphp/stomp/pull/48 and made some changes to `.travis.yml` which fixed them. I think if you pull in the second and third of my commits from PR 48, it'll work for you.

**Comment by skaffille** [comment]
@brettmc Thank you, very much. Now the build completes successfully!

**Pull request closed without merging**
