### PR TITLE
Update to more recent values

### PR DESCRIPTION
**Pull request by the-eater**
Currenlty this MR does the following

 - [x] Switch to PSR-4
 - [x] Update the tested PHP versions
 - [x] Make sure tests succeed
 - [x] Add a docker container to test the things Travis would normally do (it's not completly the same tho :()
 - [x] Make sure it works against a recent version of React
 - [x] Add tests for ActiveMQ
 - [x] squashed commits

Currently ActiveMQ tests are run without auth tests because Ubuntu ActiveMQ 5.6 for some reason doesn't allow plugins

### CODE REVIEW

**Comment by the-eater** [comment]
Hmmm the `itShouldReceiveAgainNackedMessages` test seem to fail randomly on ActiveMQ based servers

**Comment by the-eater** [comment]
So apparently ActiveMQ servers have a certain time they need before an topic is actually subscribed. :(

**Comment by WyriHaximus** [comment]
Thanks for looking into this and creating this PR :+1:

**Pull request merged**
